#Original From Daniel Duque Lozano
# -*- coding: utf-8 -*-
"""analisis_territorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AQnWOCqJUWkHUKJg-HgLbDXsLa72uWoS
"""


import pandas as pd
import os
import plotly.express as px
import matplotlib.pyplot as plt
from plotly.subplots import make_subplots
import plotly.graph_objs as go


import streamlit as st

st.set_page_config(layout='wide')


filtrado1=pd.read_csv(
    r"data/col_tria.csv",delimiter=";")

filtrado1=filtrado1.rename(columns={"predict": "Valor Proyectado", "value_thousand_dolar": "Valor real","likelihood":"Similitud de valor"})
extrange="Tamaño valor extraño"
filtrado1[extrange]=(filtrado1["Valor real"]-filtrado1["Valor Proyectado"]*2)
st.title("contratación pública")

tab0,tab1,tab2,tab3 = st.tabs(['selección','gastos según diferencias',"gastos e ingresos","ingresos"])
with tab0:
    muni = st.selectbox("Ciudad Entidad",
       filtrado1["Ciudad Entidad"])
    
    depto=st.selectbox("Departamento Entidad",
                       filtrado1["Departamento Entidad"])
    resulting=filtrado1[filtrado1["Ciudad Entidad"]=="Ciudad Entidad"]
    resulting=resulting[["Entidad","Descripción del Procedimiento","Tipo de Contrato",
                         "Valor real","Valor Proyectado",extrange,"Similitud de valor"]]
    resulting=resulting[resulting["Departamento Entidad"]==depto].sort_values("Tamaño valor extraño")
    st.dataframe(resulting.style.background_gradient(axis=None, vmin=1, vmax=5, cmap="YlGnBu"))
    
    
    
    
    
    
    
    
    
    
    
    